### ISSUE TITLE
[FEATURE] Durability

### ISSUE THREAD

**Issue by Sn0wec** [xamionex/DarkwoodCustomizer#10]
So basically durability is of course a thing with most items and for some, it is laughably low such as a staff breaking after 8 hits which doesn't help it's already terrible damage.

A simple request of maybe adding some way either to lower the amount of durability lost when using items or even prevent durability loss entirely

Anyway, thank you for your work on the mod it is greatly appreciated!

**Comment by xamionex** [comment]
Actually coming in next update, and I've been making it for a while now
Hoping everything functions correctly and right now I'm making sure so that if invalid values are inserted that it still works :)

**Comment by Sn0wec** [comment]
Ah alright, honestly good job for thinking ahead, you're doing gods work!

**Comment by xamionex** [comment]
Added in 68dbb630cb0d56139a71d392d87929b244fc893b
