### ISSUE TITLE
Rotten Items modification 

### ISSUE THREAD

**Issue by user7562** [xamionex/DarkwoodCustomizer#12]
the moment i enabled the workshop section in the Workshop.cfg, a strange medium caliber bullet recipe appeard and theres no way of removing it.

**Comment by xamionex** [comment]
Disable Load Mod Defaults First
![image](https://github.com/user-attachments/assets/a60108ef-b090-45d3-938b-90c5110343c7)

**Comment by user7562** [comment]
thanks, mind if i ask what is the item name for the rotten mushroom and bug shells? i cant seem to find them anywhere

**Comment by xamionex** [comment]
I am as clueless as you are on that, check itemlogs and test out items i guess

**Comment by user7562** [comment]
> I am as clueless as you are on that, check itemlogs and test out items i guess
> 
> Not at my pc right now so i can't check

i did, nothing shows up about those 2 items

**Comment by xamionex** [comment]
in 1.3.5 I will make the CustomItems.json file be added all the items in the game, along with their human readable names/descriptions

**Comment by xamionex** [comment]
exp_mushroom and exp_nightMushroom is your answer

**Comment by user7562** [comment]
> exp_mushroom and exp_nightMushroom is your answer

those are the standard mushroom variants, not the rotted mushroom

**Comment by xamionex** [comment]
Didn't see that, I'll check it out when I can

**Comment by xamionex** [comment]
Should work in f57d1972139e373694783946ac737a5aea41dd52
Tell me if something is wrong, haven't actually checked if any value other than type works

**Comment by xamionex** [comment]
No Replies, assuming this works
