### ISSUE TITLE
Darkwood.exe not responding

### ISSUE THREAD

**Issue by user7562** [xamionex/DarkwoodCustomizer#13]
is it only me or did the new update break the game causing it to crash mid loading

**Comment by user7562** [comment]
> Might be you, can you give me your config? (and customs too)

which configs specifically?

**Comment by xamionex** [comment]
> which configs specifically?

Your .cfg and CustomItems folder

After sending me those try resetting them, aka moving them somewhere else or deleting them
and then seeing if your game is fixed

**Comment by xamionex** [comment]
Something that might help you in the future if you run into memory issues is [process explorer](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) (Task Manager I've noticed doesn't show actual Working Set memory usage) (Also Private Bytes isn't how much the process is using, it's how many it's asked for)

**Comment by user7562** [comment]
> > which configs specifically?
> 
> Your .cfg and CustomItems folder You can even send me your whole bepinex config folder (BepInEx/Config <--- )
> 
> After sending me those try resetting them, aka moving them somewhere else or deleting them and then seeing if your game is fixed
> 
> Also from my experience the game can also crash if you run out of memory, which I've had happen because of VSCode (C++ code analysis) and DnSpyEx

heres my custim items json:
{
  "armor_light": {
    "maxDurability": 600,
    "value": 55
  },
  "shiny_rock": {
    "maxAmount": 4,
    "stackable": true,
    "value": 150
  },
  "piotrek_parts_1": {
    "maxAmount": 2,
    "stackable": true,
    "value": 132
  },
  "piotrek_parts_2": {
    "maxAmount": 3,
    "stackable": true,
    "value": 60
  },
  "piotrek_parts_3": {
    "maxAmount": 2,
    "stackable": true,
    "value": 40
  },
  "piotrek_parts_4": {
    "maxAmount": 1,
    "stackable": false,
    "value": 30
  },
  "piotrek_parts_5": {
    "maxAmount": 3,
    "stackable": true,
    "value": 32
  },
  "piotrek_parts_6": {
    "maxAmount": 1,
    "stackable": false,
    "value": 5
  },
  "meat": {
    "maxAmount": 4,
    "stackable": true,
    "value": 5
  },
  "dead_rat": {
    "maxAmount": 3,
    "stackable": true,
    "value": 3
  },
  "nail": {
    "maxAmount": 50,
    "stackable": true,
    "value": 1
  },
  "gasoline": {
    "stackable": false,
    "value": 50
  },
  "wood": {
    "maxAmount": 10,
    "stackable": true,
    "value": 5
  },
  "pipe_metal": {
    "maxAmount": 3,
    "stackable": true,
    "value": 30
  },
  "wire": {
    "maxAmount": 30,
    "stackable": true,
    "value": 6
  },
  "spring": {
    "maxAmount": 6,
    "stackable": true,
    "value": 10
  },
  "rope": {
    "maxAmount": 3,
    "stackable": true,
    "value": 10
  },
  "cable": {
    "maxAmount": 3,
    "stackable": true,
    "value": 60
  },
  "tape": {
    "maxAmount": 4,
    "stackable": true,
    "value": 50
  },
  "rag": {
    "maxAmount": 30,
    "stackable": true,
    "value": 2
  },
  "fabric": {
    "maxAmount": 2,
    "stackable": true,
    "value": 200
  },
  "lockpick": {
    "maxAmount": 20,
    "stackable": true,
    "value": 3
  },
  "battery9v": {
    "maxAmount": 10,
    "stackable": true,
    "value": 43
  },
  "pills": {
    "maxAmount": 20,
    "stackable": true,
    "value": 15
  },
  "pills_02": {
    "maxAmount": 20,
    "stackable": true,
    "value": 30
  },
  "antidote_poison": {
    "maxAmount": 5,
    "stackable": true,
    "value": 40
  },
  "firecraft_LongBarrel": {
    "maxAmount": 5,
    "stackable": true,
    "value": 185
  },
  "ammo_single_shotgun": {
    "maxAmount": 15,
    "stackable": true,
    "value": 60
  },
  "ammo_single_mediumCal": {
    "maxAmount": 18,
    "stackable": true,
    "value": 72
  },
  "ammo_clip_smallCal": {
    "maxAmount": 4,
    "stackable": true,
    "value": 100
  },
  "ammo_clip_mediumCal": {
    "maxAmount": 3,
    "stackable": true,
    "value": 200
  },
  "beartrap": {
    "damage": 52,
    "value": 35
  },
  "chainTrap": {
    "damage": 30,
    "value": 20
  },
  "stick": {
    "damage": 2,
    "maxDurability": 600,
    "value": 4
  },
  "plank_nails": {
    "damage": 4,
    "maxDurability": 810,
    "value": 6
  },
  "knife": {
    "damage": 11,
    "maxDurability": 1100,
    "repairable": true,
    "repairrequirements": 1,
    "value": 50
  },
  "sickle": {
    "damage": 13,
    "maxDurability": 1150,
    "value": 15
  },
  "shovel": {
    "damage": 15,
    "maxDurability": 1100,
    "value": 200
  },
  "pitchfork": {
    "damage": 20,
    "maxDurability": 980,
    "value": 150
  },
  "axe": {
    "damage": 60,
    "maxDurability": 2500,
    "value": 310
  },
  "weapon_pistol_03_oneShot": {
    "damage": 20,
    "value": 44
  },
  "weapon_shotgun_05_oneShot": {
    "damage": 7,
    "value": 50
  },
  "weapon_pistol_01_pellet": {
    "damage": 4,
    "value": 5
  },
  "weapon_pistol_02_semi": {
    "damage": 9,
    "value": 100
  },
  "weapon_submachinegun_01_full": {
    "damage": 9,
    "value": 120
  },
  "weapon_shotgun_01_breakAction_double": {
    "damage": 9,
    "value": 220
  },
  "weapon_shotgun_03_singleShot": {
    "damage": 9,
    "value": 220
  },
  "weapon_assault_01_burst": {
    "damage": 18,
    "value": 300
  },
  "weapon_flamethrower_homeMade": {
    "damage": 4,
    "value": 180
  },
  "fists": {
    "iconType": "fists",
    "maxAmount": 0,
    "stackable": false
  },
  "hammer": {
    "iconType": "hammer",
    "maxAmount": 0,
    "stackable": false
  }
}

i dont understand "Your .cfg" theres alot of files that have the suffix .cfg

**Comment by xamionex** [comment]
Do you not have 7zip?
just zip your Bepinex/Config folder and send it here

**Comment by xamionex** [comment]
![image](https://github.com/user-attachments/assets/d50a2fba-0d10-47e0-b9c4-9cc7be2e9871)

**Comment by user7562** [comment]
[config.zip](https://github.com/user-attachments/files/17213445/config.zip)

**Comment by xamionex** [comment]
Fixed in 1b3f8e6cd6a916316236d543610b3baea617b38c
Also added item logging when its changed, so if this happens again, do enable logs and see if the game throws out errors, if it does, create another issue and put the log there along with your config, thanks!

**Comment by user7562** [comment]
> Fixed in [1b3f8e6](https://github.com/xamionex/DarkwoodCustomizer/commit/1b3f8e6cd6a916316236d543610b3baea617b38c) Also added item logging when its changed, so if this happens again, do enable logs and see if the game throws out errors, if it does, create another issue and put the log there along with your config, thanks!

just checked, new version fixed the infinite loading time. game works fine but ive noticed that the workbench now turned into vanilla, all those custom recipes are gone. i did check the log and no errors were found.

**Comment by xamionex** [comment]
Only*reading* the values from the json was changed
Just download your old config you sent me and place it in bepinex
