### ISSUE TITLE
Military flamethrower disabling inventory

### ISSUE THREAD

**Issue by user7562** [xamionex/DarkwoodCustomizer#15]
once you equip the military flamethrower you are unable to use your inventory or switch weapons. gun does not function.

**Comment by xamionex** [comment]
the military flamethrower is used in a dream sequence or something, I don't remember, that's why I set up my recipe for it to use the homemade one, just use the default config

**Comment by xamionex** [comment]
Couldn't replicate, read above comment if you still have this issue.
