### ISSUE TITLE
Custom night events

### ISSUE THREAD

**Issue by user7562** [xamionex/DarkwoodCustomizer#16]
ability to customize the min/max and chance of night events

**Comment by xamionex** [comment]
After trying to understand how it works I've deemed this very hard to implement, sorry
There's just too much to take in here and too much modification for it to work properly and not to say testing this would be a nightmare

**Comment by user7562** [comment]
> After trying to understand how it works I've deemed this very hard to implement, sorry There's just too much to take in here and too much modification for it to work properly and not to say testing this would be a nightmare

i see, understandable
