### ISSUE TITLE
Music/transition not timed correctly after modifying night lenght

### ISSUE THREAD

**Issue by user7562** [xamionex/DarkwoodCustomizer#17]
After modifying the lenght of night time, the music doesnt play at 7am but it plays somewhere around 4-5am or depending on the float you've set in the config it would play sooner. After the night finishes, there is no transition, yes the white screen appears but it takes about 5-10 seconds for the game to process that the night has finished. In that period your stuck in a limbo of 8am with no trader.

**Comment by xamionex** [comment]
This works for me, just to make sure what is your time config

**Comment by user7562** [comment]
> This works for me, just to make sure what is your time config

what?

**Comment by xamionex** [comment]
Time modification works perfectly for me, can you give me your config

**Comment by user7562** [comment]
> Time modification works perfectly for me, can you give me your config

[Time.zip](https://github.com/user-attachments/files/17265974/Time.zip)
heres my time config

**Comment by xamionex** [comment]
> [Time.zip](https://github.com/user-attachments/files/17265974/Time.zip) heres my time config

well of course it's gonna transfer 5 seconds late, you set the interval to 5 seconds
it waits 5 seconds then updates the time, which includes calculating when the night ends
gonna update the documentation but yeah, this works as intended as you were never meant to have 5 second time interval and only 1s and 0.75s if it was night

**Comment by xamionex** [comment]
I guess just make sure not to go above 2 or something, it's still 2.25x slower than normal for night time
The time update process goes like this:

- Set time to 0 (day starts)
- Every interval add 2 seconds (check if its night time, if it is use night interval)
- Set interval respectively (with the mod you change this)
- Every x (x being interval you set with the mod) seconds update the time

**Comment by user7562** [comment]
> I guess just make sure not to go above 2 or something, it's still 2.25x slower than normal for night time The time update process goes like this:
> 
> * Set time to 0 (day starts)
> * Every interval add 2 seconds (check if its night time, if it is use night interval)
> * Set interval respectively (with the mod you change this)
> * Every x (x being interval you set with the mod) seconds update the time
> 
> The CurrentTime variable in Controller is an int, I can't really change the 2 seconds part to add decimals to it since it'll get rounded I could make my mod manage the time but that would need syncing between the game and my mod and I wouldn't know how to manage that (the actual update time method being a delegate doesn't help either)

alright, i have a question regarding some item names because i cant seem to find them. (pellet rifle,bug shell, auto shotgun and uzi)

**Comment by xamionex** [comment]
They should be in the itemlog.log but if they arent just wait for me to eventually add them to the default config

**Comment by user7562** [comment]
> They should be in the itemlog.log but if they arent just wait for me to eventually add them to the default config

they are not
