### ISSUE TITLE
[BUG] Darkwood, picking up mushrooms only adds a beartrap to your inventory, even if the beartrap setting is turned off.  Can't get mushrooms now :(

### ISSUE THREAD

**Issue by Dakayo** [xamionex/DarkwoodCustomizer#2]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions:**

- Mod: x.x.x
- Game: 1.4.2

**Additional context**

**Comment by xamionex** [comment]
Checking this out now, thanks for the report

**Comment by xamionex** [comment]
Fixed in c72fabab1a03271f480adc6a78c4e9127813c133
