### ISSUE TITLE
Customizable npc loot

### ISSUE THREAD

**Issue by user7562** [xamionex/DarkwoodCustomizer#20]
self explanatory. option to add random amounts of said item would be good to have as well.

**Comment by xamionex** [comment]
Test in 1.4.3 please
CRI's are generated when loading a save or whatever you're wanting to configure, gets spawned by the game

**Comment by user7562** [comment]
> Test in 1.4.3 please CRI's are generated when loading a save or whatever you're wanting to configure gets spawned by the game

config file is blank

**Comment by user7562** [comment]
> Did you enable the Custom Random Inventories option in the cfg?

yes

**Comment by xamionex** [comment]
Try making a new save, and if loading it doesnt generate all the cri's try making it to day 2 on that same save

**Comment by user7562** [comment]
> Try making a new save, and if loading it doesnt generate all the cri's try making it to day 2 on that same save

yes, that did the trick. i also figured out that the the shell item from bugs is actually called chitin. Other than that the log keeps spewing errors saying the following:

[Error  :DarkwoodCustomizer] [USERCUSTOMRECIPES] Item weapon_submachine_full does not exist, stopping as to not break the plugin!

this same error popped up when i had this item registered in the customitems file as well

**Comment by xamionex** [comment]
That happens in this [line of code here](https://github.com/xamionex/DarkwoodCustomizer/blob/5c76f1b42c25c8d1983cea8dd3e460c250ecf6ef/Workbench.cs#L57) in case when the item being loaded, wasn't loaded by the game and my plugin also can't load it, which means it's a NRE (doesn't exist), try finding something similar to that in the itemlog

**Comment by user7562** [comment]
> That happens in this [line of code here](https://github.com/xamionex/DarkwoodCustomizer/blob/5c76f1b42c25c8d1983cea8dd3e460c250ecf6ef/Workbench.cs#L57) in case when the item being loaded, wasn't loaded by the game and my plugin also can't load it, which means it's an NRE (NullReferenceException, aka doesn't exist), try finding something similar to that in the itemlog, maybe it's called something else

i literally just copy pasted that item's name from the item log. you must've coded it wrong

**Comment by xamionex** [comment]
Can you try weapon_submachine_01_full instead
And if that doesnt work try witthout the _full

**Comment by user7562** [comment]
> Can you try weapon_submachine_01_full instead And if that doesnt work try without the _full

yes, that did it, now it works thanks. Now i have a question on how the chance values work. if the chance is set to 1.0 does that mean its a 100% chance of spawning? or is it 0.100 instead?

**Comment by xamionex** [comment]
1 is 100%

**Comment by user7562** [comment]
> 1 is 100%

1 as in 1.0? or just 1

**Comment by xamionex** [comment]
> > 1 is 100%
> 
> 1 as in 1.0? or just 1

Yes

**Comment by user7562** [comment]
> > > 1 is 100%
> > 
> > 
> > 1 as in 1.0? or just 1
> 
> Yes

so if i want the chance to be 50% how do i do it? i keep seeing the other item's chances being 0.598 or 0.678 for example,

**Comment by xamionex** [comment]
I'd say 0.5

**Comment by user7562** [comment]
> I'd say 0.5
and how do i make the chance between say like 20 or 40? do i just do 0.24 and 0.33?

**Comment by xamionex** [comment]
It's a float and is probably used like 100% chance being 1.0 and 0.01 being 1% chance
I haven't looked into the code for it to see how it functions but that's how i'd do it

**Comment by user7562** [comment]
> It's a float and is probably used like 100% chance being 1.0 and 0.01 being 1% chance I haven't looked into the code for it to see how it functions but that's how i'd do it

i see, thanks.

**Comment by user7562** [comment]
> Test in 1.4.3 please CRI's are generated when loading a save or whatever you're wanting to configure gets spawned by the game

its partially working, so far ive only seen it work with traders nothing else

**Comment by xamionex** [comment]
Can't figure this out for the life of me, this will take a while

**Comment by xamionex** [comment]
Added in 1.4.6, check out the [wiki](https://github.com/xamionex/DarkwoodCustomizer/wiki) if you need help with it
