### ISSUE TITLE
[BUG] Cant access button prompts at epilogue apartment

### ISSUE THREAD

**Issue by Hazen063** [xamionex/DarkwoodCustomizer#23]
**Describe the bug**
You can examine people but when it comes to looking inside containers the box itself bugs and and goes away after you exit, then making no more prompts available

**To Reproduce**

1. Go inside apartment 
2. Click on mailbox and other interactables
3. See them bugged out
4. Cant see button prompts anymore

**Expected behavior**
No longer be able to interact with the world, stuck in the apartment

**Versions:**

- Mod: Yours
- Game: Latest 1.4.2
[1_4Save.zip](https://github.com/user-attachments/files/18240555/1_4Save.zip)

**Comment by xamionex** [comment]
Fixed in da4383266a8b3cecbc6c5c17cd52db757588c75f
Thanks for the save, saved a lot of time ^^

**Comment by Hazen063** [comment]
Ah I see haha, new all this
