### ISSUE TITLE
[BUG] Health isn't maximum on load. 

### ISSUE THREAD

**Issue by Dakayo** [xamionex/DarkwoodCustomizer#3]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions:**

- Mod: x.x.x
- Game: 1.4.2

**Additional context**

**Comment by xamionex** [comment]
Will check out
FYI: the title is supposed to be a short line explaining the issue and then you're supposed to enter the full issue below

**Comment by Dakayo** [comment]
> Will check out FYI: the title is supposed to be a short line explaining the issue and then you're supposed to enter the full issue below

sorry about that

**Comment by xamionex** [comment]
Anyway I'm gonna crack down on this issue and release an update soon, do make more issues if you find any, thank you

**Comment by xamionex** [comment]
Fixed in cd90d0625861e22080e3438a15f7767648412ee0

**Comment by xamionex** [comment]
Actually just realized I've made an issue, it should load your current health and not the maximum you have always

**Comment by xamionex** [comment]
I'm not sure how to fix this, are you fine with this random cheese I've just created haha

**Comment by Dakayo** [comment]
> I'm not sure how to fix this, are you fine with this random save scumming I've just created haha

it's ok, i can get use to it. I just thought it should be addressed.

**Comment by xamionex** [comment]
No updates, assuming fixed
