### ISSUE TITLE
[BUG] All config reverts to default in Chapter 2. 

### ISSUE THREAD

**Issue by Dakayo** [xamionex/DarkwoodCustomizer#4]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions:**

- Mod: x.x.x
- Game: 1.4.2

**Additional context**

**Comment by Dakayo** [comment]
When I first enter the chapter 2 hideout, every config resets to default value until I load a save or reboot the game.

**Comment by xamionex** [comment]
This is gonna be hard to debug, do you have a save just before chapter 2 by any chance?

**Comment by Dakayo** [comment]
> This is gonna be hard to debug, do you have a save just before chapter 2 by any chance?

No i don't. But i can restart and speedrun through it, give me a minute.

**Comment by xamionex** [comment]
You can zip it and place it in a comment here
The save is located at `%AppData%\..\LocalLow\Acid Wizard Studio\Darkwood\1_4Save`
and then inside one of the profile folders according to the profile slot ingame

**Comment by xamionex** [comment]
I'm going to be offline for a while, will continue this issue tomorrow

**Comment by Dakayo** [comment]
nvm, apparently it happens randomly when you load a save.

**Comment by Dakayo** [comment]
> I'm going to be offline for a while, will continue this issue tomorrow

Nvm, it's good now. I guess it just happens randomly whenever you load a game or whenever the game loads to the next chapter.

**Comment by xamionex** [comment]
> Nvm, it's good now. I guess it just happens randomly whenever you load a game or whenever the game loads to the next chapter.

Might be related to #3 since I changed from loading on initialization (basically first load) to load on character creation (when character is created)

**Comment by xamionex** [comment]
Reopen if this happens again
