### ISSUE TITLE
[BUG] Custom recipes aren't showing up.

### ISSUE THREAD

**Issue by Dakayo** [xamionex/DarkwoodCustomizer#5]
**Describe the bug**
It says that you've added custom recipes but I don't see them on the workbench. I've upgraded it to levels 3 and 8 and they're not popping up in the recipes. I went to the config folder and enabled "workbench.cfg" still not working.

**To Reproduce**

1. Go to 'workbench'
2. Click on 'upgrade workbench'

**Expected behavior**

**Screenshots**

**Versions:**

- Mod: 1.2.0 *experimental* 
- Game: 1.4.2

**Additional context**

**Comment by xamionex** [comment]
Will try to fix in a hotfix and tell me if that works

**Comment by xamionex** [comment]
By the way, just so you know you can also open feature requests here, I saw you commenting on nexus for features, simply go to issues, create a new one and pick the Feature request template instead
also, think of the big box below the title as your comment on the matter, you can literally put anything and you don't really have o follow the template, it's just there for standardization

**Comment by xamionex** [comment]
Anyway it seems that something broke the setting recipes part, might take a bit longer
Also reloading the configs was an issue so restarting the game is required for refreshing configs on 1.2.0
This issue is fixed in 1.2.1

**Comment by Dakayo** [comment]
> Anyway it seems that something broke the setting recipes part, might take a bit longer Also reloading the configs was an issue so restarting the game is required for refreshing configs on 1.2.0 This issue is fixed in 1.2.1 which I will release when I fix the recipes

Take your time, man. This is great so far.

**Comment by xamionex** [comment]
Can you check if it works in v1.2.1

**Comment by Dakayo** [comment]
> Can you check if it works in v1.2.1

It works now, thanks!

**Comment by xamionex** [comment]
No problem, thank you too for reporting :)
