### ISSUE TITLE
[FEATURE] Lists of cool recipes for the workbench. 

### ISSUE THREAD

**Issue by Dakayo** [xamionex/DarkwoodCustomizer#6]
1. Assault Rifle  
2. Flame Thrower (can be repaired using gasoline)
3. Sub Machine Gun
4. Pellet gun (needs recipe for pellets or can be sold by traders) 

(optional) Make traders have 2x or 10x the stock of available recourses.

**Comment by Dakayo** [comment]
Ah, That's cool, but I'm not good at writing stuff like that. I can't even write code to save my life, lol

**Comment by xamionex** [comment]
I'll get around to it sometime after I add damage to custom characters

**Comment by Dakayo** [comment]
I appreciate that. Thanks!

**Comment by xamionex** [comment]
Flamethrower is added past 1.2.9 and can be reloaded or repaired using gasoline
